### ISSUE TITLE
Problems using digitaljs

### ISSUE THREAD

**Issue by lcbcFoo** [tilk/digitaljs#11]
Hi!

I am trying to use digitaljs, but I am facing problems using the npm module. I am new to Javascript so I might be missing something basic. Here is what I did:

- created a simple index.html

<details>
<summary>index.html</summary>

```
<!doctype html>
<html>
  <head>
    <title>Test digitaljs</title>
  </head>
  <body>
      <div name="#paper">
      </div>
  </body>
</html>
```

</details>

- Created a simple index.js based on the code from README

<details>
<summary>index.js</summary>

```
// I assume this line is necessary - without it node complains digitaljs is not defined
digitaljs = require('digitaljs')

// create the simulation object
// I know an actual input must go here, but code doesn't reach this point
const circuit = new digitaljs.Circuit(input_goes_here);
// display on #paper
const paper = circuit.displayOn($('#paper'));
// activate real-time simulation
circuit.start();
```

</details>

- When I run node I get:

```
$ node index.js
/home/foo/workspace/block_v/workspaces/test/node_modules/digitaljs/src/index.js:3
import 'babel-polyfill';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1063:16)
    at Module._compile (internal/modules/cjs/loader.js:1111:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/foo/workspace/block_v/workspaces/test/index.js:1:13)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
```

Any directions would be appreciated

**Comment by tilk** [comment]
This is not an issue, but a support request. I don't provide support for DigitalJS nor Javascript, sorry.

As for your problem, it looks like you are a beginner, and you need to learn some things about NPM and maybe Webpack.
